### ISSUE TITLE
Does this work with jQuery-UI 1.11?

### ISSUE THREAD

**Issue by slauyama** [dsbaars/jq-ui-draggable-collision#3]
I know that this isn't your code and just a mirror but does anyone know if this code works with jQuery-UI 1.11.0

**Comment by dsbaars** [comment]
Changed 2 characters of codes for you, it works. Asking the question took more time...

**Comment by slauyama** [comment]
Thank you for answering back so quickly. ~~I'm sorry this seems like a dumb question but I have been looking over both libraries and have been unable to get it to work. What are the characters of code are you talking about?~~

Never mind. I was able to figure it out. For anyone else wondering you have to change the reference from 

``` javascript
$(this).data("draggable") 
```

to 

``` javascript
$(this).data("uiDragggable")
```
