### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by alilishan-omniphics** [dsbaars/jq-ui-draggable-collision#5]
Hi downladed and tried ur examples but Iam getting this error "$(...).collision is not a function"

![image](https://user-images.githubusercontent.com/16457400/40471047-05e4c85a-5f68-11e8-9450-6663d2f984ad.png)

Please help

**Comment by alilishan-omniphics** [comment]
ok found 👍 thanks 🤕

**Comment by SeaCatWiz** [comment]
@alilishan-omniphics how did you solve the problem? I faced the same exception.
UPD For those who encounter the problem - make sure you import/include the jquery-collision module.
